### ISSUE TITLE
微信支付提示v3请求构造异常！

### ISSUE THREAD

**Issue by chaobear** [binarywang/weixin-java-pay-demo#103]
sdk 4.1.0，微信jsapi支付，jdk版本1.8
统一下单接口提示：v3请求构造异常！

**Comment by chaobear** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/51193643/180406615-5a24ee4a-f1ab-4512-b331-fc5ef3374398.png">

**Comment by chaobear** [comment]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/51193643/180942984-f419c0d6-77fe-426a-8195-55df882f024e.png">

**Comment by xiapengfeifei** [comment]
证书问题 检查下  下载的两个文件  一个是私钥 apiclient_key.pem  一个是证书apiclient_cert.pem

**Comment by renanmin** [comment]
这是来自QQ邮箱的疫情自动回复邮件。
 
您好，我最近正在疫情中，无法亲自回复您的邮件。我将在疫情结束后，尽快给您回复。

**Comment by tedux** [comment]
遇到同样的问题，请问改怎么解决呢？服务器里面的证书路径改成绝对路径也不行

**Comment by tedux** [comment]
Caused by: java.lang.IllegalArgumentException: java.security.InvalidKeyException: Illegal key size
at com.github.binarywang.wxpay.v3.util.AesUtils.decryptToString(AesUtils.java:74) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.deserializeToCerts(AutoUpdateCertificatesVerifier.java:200) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.autoUpdateCert(AutoUpdateCertificatesVerifier.java:166) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.<init>(AutoUpdateCertificatesVerifier.java:109) ~[weixin-java-pay-4.4.0.jar!/:na]
at com.github.binarywang.wxpay.config.WxPayConfig.initApiV3HttpClient(WxPayConfig.java:285) ~[weixin-java-pay-4.4.0.jar!/:na]
... 56 common frames omitted
Caused by: java.security.InvalidKeyException: Illegal key size
at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039) ~[na:1.8.0_121]
at javax.crypto.Cipher.implInit(Cipher.java:805) ~[na:1.8.0_121]
at javax.crypto.Cipher.chooseProvider(Cipher.java:864) ~[na:1.8.0_121]
at javax.crypto.Cipher.init(Cipher.java:1396) ~[na:1.8.0_121]
at javax.crypto.Cipher.init(Cipher.java:1327) ~[na:1.8.0_121]
at com.github.binarywang.wxpay.v3.util.AesUtils.decryptToString(AesUtils.java:67) ~[weixin-java-pay-4.4.0.jar!/:na]
... 60 common frames omitted

**Comment by hhzhi** [comment]
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 3f

**Comment by hhzhi** [comment]
同样的问题。

**Comment by hhzhi** [comment]
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 3f

**Comment by hhzhi** [comment]
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 3f

**Comment by hhzhi** [comment]
同样的问题，有解决的吗？Caused by: java.lang.IllegalArgumentException: Illegal base64 character 3f

**Comment by hhzhi** [comment]
已解决。证书密钥提前 base64 encode 一下

**Comment by AnisJiang** [comment]
> 已解决。证书密钥提前 base64 encode 一下
哪个证书密钥encode?

**Comment by gx-russel** [comment]
我是改了个JDK版本就行了[加解密的异常处理办法](https://github.com/Wechat-Group/WxJava/wiki/%E5%8A%A0%E8%A7%A3%E5%AF%86%E7%9A%84%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E5%8A%9E%E6%B3%95)
