### ISSUE TITLE
支付统一下单报结果解析异常

### ISSUE THREAD

**Issue by codemanben** [binarywang/weixin-java-pay-demo#115]
你好，支付统一下单报结果解析异常：com.thoughtworks.xstream.mapper.CannotResolveClassException: html
大概是什么原因呢，谢谢！

* WxJava 版本号: 4.4.0

`com.thoughtworks.xstream.mapper.CannotResolveClassException: html
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:81)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:135)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1421)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1399)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1284)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1275)
	at com.github.binarywang.wxpay.bean.result.BaseWxPayResult.fromXML(BaseWxPayResult.java:154)
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.unifiedOrder(BaseWxPayServiceImpl.java:683)
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.createOrder(BaseWxPayServiceImpl.java:586)`

**Comment by binarywang** [comment]
html?  看看原始报文是啥

**Comment by codemanben** [comment]
> html? 看看原始报文是啥

抱歉，原因是不小心开了沙盒测试，结果微信接口请求地址404了，感谢回复！
