### ISSUE TITLE
acquire timeouted

### ISSUE THREAD

**Issue by ivvtom** [binarywang/weixin-java-pay-demo#72]
java.lang.RuntimeException: acquire timeouted
        at me.chanjar.weixin.common.util.locks.JedisDistributedLock.lock(JedisDistributedLock.java:29) ~[weixin-java-common-3.9.0.jar!/:na]
        at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.getTicket(BaseWxMpServiceImpl.java:151) ~[weixin-java-mp-3.9.0.jar!/:na]

**Comment by binarywang** [comment]
获取锁超时，自己处理即可
