### ISSUE TITLE
传相同的参数，为什么微信分本地项目能通，部署到linux服务器上面创建订单接口时候报构建v3异常呢

### ISSUE THREAD

**Issue by pandazhang520** [binarywang/weixin-java-pay-demo#79]
求救

**Comment by pandazhang520** [comment]
异常图片：![image](https://user-images.githubusercontent.com/52320457/118168586-88f5f500-b417-11eb-9f60-e22ee58c9c98.png)

异常代码
Caused by: java.lang.IllegalArgumentException: java.security.InvalidKeyException: Illegal key size
        at com.github.binarywang.wxpay.v3.util.AesUtils.decryptToString(AesUtils.java:75) ~[weixin-java-pay-4.0.0.jar:na]
        at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.deserializeToCerts(AutoUpdateCertificatesVerifier.java:171) ~[weixin-java-pay-4.0.0.jar:na]
        at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.autoUpdateCert(AutoUpdateCertificatesVerifier.java:145) ~[weixin-java-pay-4.0.0.jar:na]
        at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.<init>(AutoUpdateCertificatesVerifier.java:95) ~[weixin-java-pay-4.0.0.jar:na]
        at com.github.binarywang.wxpay.config.WxPayConfig.initApiV3HttpClient(WxPayConfig.java:268) ~[weixin-java-pay-4.0.0.jar:na]
        ... 108 common frames omitted
Caused by: java.security.InvalidKeyException: Illegal key size
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039) ~[na:1.8.0_122]
        at javax.crypto.Cipher.implInit(Cipher.java:805) ~[na:1.8.0_122]
        at javax.crypto.Cipher.chooseProvider(Cipher.java:864) ~[na:1.8.0_122]
        at javax.crypto.Cipher.init(Cipher.java:1396) ~[na:1.8.0_122]
        at javax.crypto.Cipher.init(Cipher.java:1327) ~[na:1.8.0_122]
        at com.github.binarywang.wxpay.v3.util.AesUtils.decryptToString(AesUtils.java:68) ~[weixin-java-pay-4.0.0.jar:na]
        ... 112 common frames omitted

**Comment by binarywang** [comment]
这个不是常见问题吗？wxjava的wiki里的
