### ISSUE TITLE
调用api v3接口统一下单加载证书异常

### ISSUE THREAD

**Issue by itcrazy2019** [binarywang/weixin-java-pay-demo#94]
# 问题（提问前，请确保阅读过项目首页说明以及SDK wiki文档相关内容）

### 简要描述
调用api v3接口统一下单加载证书异常，对应的com/google/common/base/CharMatcher类中没有whitespace()方法

### 版本情况

* WxJava 版本号:  4.2.0

### 期待结果
解决异常

### 实际情况
java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.whitespace()Lcom/google/common/base/CharMatcher;
	at com.github.binarywang.wxpay.v3.util.AesUtils.decryptToString(AesUtils.java:71) ~[weixin-java-pay-4.2.0.jar:na]
	at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.deserializeToCerts(AutoUpdateCertificatesVerifier.java:172) ~[weixin-java-pay-4.2.0.jar:na]
	at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.autoUpdateCert(AutoUpdateCertificatesVerifier.java:146) ~[weixin-java-pay-4.2.0.jar:na]
	at com.github.binarywang.wxpay.v3.auth.AutoUpdateCertificatesVerifier.<init>(AutoUpdateCertificatesVerifier.java:96) ~[weixin-java-pay-4.2.0.jar:na]
	at com.github.binarywang.wxpay.config.WxPayConfig.initApiV3HttpClient(WxPayConfig.java:267) ~[weixin-java-pay-4.2.0.jar:na]
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.createApiV3HttpClient(WxPayServiceApacheHttpImpl.java:275) ~[weixin-java-pay-4.2.0.jar:na]
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.postV3(WxPayServiceApacheHttpImpl.java:93) ~[weixin-java-pay-4.2.0.jar:na]
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.unifiedOrderV3(BaseWxPayServiceImpl.java:696) ~[weixin-java-pay-4.2.0.jar:na]
	at com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.createOrderV3(BaseWxPayServiceImpl.java:683) ~[weixin-java-pay-4.2.0.jar:na]

### 重现步骤
1. 
2. 
3. 

### 日志
__日志内容如果过多，请将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by itcrazy2019** [comment]
问题一解决，和swagger的包冲突了，解决方法：在swagger的相关依赖中排除guava依赖，如：
<dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger-ui</artifactId>
      <version>${io.springfox.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger2</artifactId>
      <version>${io.springfox.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
